name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_JWT_SECRET: "TestSecret"
      ORGANIZER_JWT_SECRET: "TestSecret"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Add passport
        run: npm i --save @nestjs/passport passport

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Lint project
        run: npm run lint